# Common error code
CODE_OK = 0
CODE_SYSTEM_ERROR = 1
CODE_PARAM_WRONG = 2
CODE_LINK_EXPIRED = 3
CODE_NOT_LOGINED = 4
CODE_ILLEGAL_REQUEST = 5
CODE_NO_PERMISSION = 6
CODE_RESOURCE_NOT_FOUND = 7
CODE_RESOURCE_DUPLICATED = 8

# User error code
CODE_USER_INVISIBLE = 1000
CODE_USER_PASSWORD_WRONG = 1001

# Error message
MESSAGES = {
    CODE_OK: "成功",
    CODE_SYSTEM_ERROR: "系统错误",
    CODE_PARAM_WRONG: "参数错误",
    CODE_LINK_EXPIRED: "链接过期",
    CODE_NOT_LOGINED: "未登录",
    CODE_ILLEGAL_REQUEST: "非法请求",
    CODE_NO_PERMISSION: "无权操作",
    CODE_RESOURCE_NOT_FOUND: "资源未找到",
    CODE_RESOURCE_DUPLICATED: "资源重复",

    CODE_USER_INVISIBLE: "用户不可见",
    CODE_USER_PASSWORD_WRONG: "密码错误",
}
